api pytest:
    image: alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
    services:
        - name: mooseagency/postgresql:12.3-1@sha256:a5a65569456f221ee1f8a0b3b4e2d440eb5830772d9440c9b30b1dbfd454c778
          alias: postgresql
          command:
              - postgres
              - -cfsync=off
              - -cfull_page_writes=off
              - -cautovacuum=off
    variables:
        POSTGRESQL_INITDB_DATABASES: "admin:secret@default"
    script:
        - echo "Renovate test"
